# {% set version = "2.0.4" %}

package:
  name: switch_model
  version: 2.0.6

source:
  # url: https://pypi.io/packages/source/s/switch_model/switch_model-{{ version }}.tar.gz
  # can't automate URL generation lately; just have to read URL and SHA from 
  # https://pypi.org/project/switch-model/#files 
  url: https://files.pythonhosted.org/packages/98/fb/332ff8d29b9cf6b271d2fc94b5cdd482ce0158d04d5858f2f63a129a353f/switch_model-2.0.6.tar.gz
  sha256: 179919ea051821be2e8369a7ea978a92341e8969c47962ab3cf84e55a73ff68b

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - switch=switch_model.main:main
requirements:
  build:
  host:
    - python
    - pip
  run:
    - python >=2.7.12
    - pyomo <=5.6.8
    - pyutilib <=5.7.3
    - pint
    - testfixtures
    - pandas
    - glpk

test:
  imports:
    - switch_model
  source_files:
    - run_tests.py
    - switch_model
    - examples
    - tests
  commands:
    - switch --help
    - switch test
    - python run_tests.py

about:
  home: http://switch-model.org
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A modern platform for planning high-renewable power systems'
  description: |
    Switch 2.0 is an open-source modeling platform for planning transitions to
    low-emission electric power grids, designed to satisfy 21st century grid
    planning requirements. Switch is capable of long-, medium- and short-term
    planning of investments and operations with conventional or smart grids,
    integrating large shares of renewable power, storage and/or demand response.
    Applications include integrated resource planning, investment planning,
    economic and policy analyses as well as basic research.
  doc_url: http://switch-model.org
  dev_url: https://github.com/switch-model/switch

extra:
  recipe-maintainers:
    - mfripp
