{% set pyomo_ver = ">=5.7.0,<=6.4.2" %}
{% set python_ver = ">=3.7.0,<3.11.0a0" %}
{% set pyutilib_ver = ">=6.0.0,<=6.0.0" %}
{% set name = "switch_model" %}
{% set version = "2.0.8" %}
{% set build_num = 0 %}
{% set python_ver = ">=3.7.0,<3.11.0a0" %}
{% set pyomo_ver = ">=5.7.0,<=6.4.2" %}
{% set pyutilib_ver = ">=6.0.0,<=6.0.0" %}
# Get hash from https://pypi.org/project/switch-model/#files
# There is also an alternative URL there if the one above doesn't work (may
# take time to propagate?)
{% set sha = "d2d6cc5baa7e753388e6f16cb6f00ab7f5171a7eb7849e5a0d99fc17c40214c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  number: {{ build_num }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - switch=switch_model.main:main
requirements:
  build:
  host:
    - python
    - pip
  run:
    - python {{ python_ver }}
    - pyomo {{ pyomo_ver }}
    - pyutilib {{ pyutilib_ver }}
    - pint
    - testfixtures
    - pandas
    - glpk

test:
  imports:
    - switch_model
  source_files:
    - run_tests.py
    - switch_model
    - examples
    - tests
  commands:
    - switch --help
    - switch test
    - python run_tests.py

about:
  home: http://switch-model.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A modern platform for planning high-renewable power systems'
  description: |
    Switch 2.0 is an open-source modeling platform for planning transitions to
    low-emission electric power grids, designed to satisfy 21st century grid
    planning requirements. Switch is capable of long-, medium- and short-term
    planning of investments and operations with conventional or smart grids,
    integrating large shares of renewable power, storage and/or demand response.
    Applications include integrated resource planning, investment planning,
    economic and policy analyses as well as basic research.
  doc_url: http://switch-model.org
  dev_url: https://github.com/switch-model/switch

extra:
  recipe-maintainers:
    - mfripp
