# {% set version = "2.0.4" %}

package:
  name: switch_model
  version: 2.0.5.post2

source:
  # url: https://pypi.io/packages/source/s/switch_model/switch_model-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/e9/b3/fd2dcec5972a846036b0ab3e821279af72e51e06c35eed46cbcc15375724/switch_model-2.0.5.post2.tar.gz
  sha256: e87c71211d4a436dba70e217005eaff157a744d191be9e42a59d382f8f38e542

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - switch=switch_model.main:main

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - pyomo <5.6.9a0
    - pyutilib <6.0a0
    - pint
    - testfixtures
    - pandas
    - glpk

test:
  imports:
    - switch_model
  source_files:
    - run_tests.py
    - switch_model
    - examples
    - tests
  commands:
    - switch --help
    - switch test
    - python run_tests.py

about:
  home: http://switch-model.org
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A modern platform for planning high-renewable power systems'
  description: |
    Switch 2.0 is an open-source modeling platform for planning transitions to
    low-emission electric power grids, designed to satisfy 21st century grid
    planning requirements. Switch is capable of long-, medium- and short-term
    planning of investments and operations with conventional or smart grids,
    integrating large shares of renewable power, storage and/or demand response.
    Applications include integrated resource planning, investment planning,
    economic and policy analyses as well as basic research.
  doc_url: http://switch-model.org
  dev_url: https://github.com/switch-model/switch

extra:
  recipe-maintainers:
    - mfripp
