{% set name = "switch_model" %}
{% set version = "2.0.9.post0" %}
{% set build_num = 0 %}
{% set python_min = "3.7.2" %}
{% set python_ver = ">=3.7.2,<3.14.0a0" %}
{% set pyomo_ver = ">=6.0.0,<=6.9.1" %}
# Get hash from https://pypi.org/project/switch-model/#files
# There is also an alternative URL there if the one below doesn't work (may
# take time to propagate?)
{% set sha = "a45cef57c96265028df30314a9b4d87042c3fcd6edbb5b3d7c050fbc7aca8051" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  number: {{ build_num }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - switch=switch_model.main:main
requirements:
  build:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pyomo {{ pyomo_ver }}
    - pint
    - testfixtures
    - pandas
    - glpk

test:
  # Starting 1/1/2025, conda-forge recommends testing with minimum supported Python version
  # to prevent incompatibilities from getting out the door 
  # https://github.com/conda-forge/cfep/blob/main/cfep-25.md
  requires:
    - python {{ python_min }}

  imports:
    - switch_model
  source_files:
    - run_tests.py
    - switch_model
    - examples
    - tests
  commands:
    - switch --help
    - switch test
    - python run_tests.py

about:
  home: http://switch-model.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A modern platform for planning high-renewable power systems'
  description: |
    Switch 2.0 is an open-source modeling platform for planning transitions to
    low-emission electric power grids, designed to satisfy 21st century grid
    planning requirements. Switch is capable of long-, medium- and short-term
    planning of investments and operations with conventional or smart grids,
    integrating large shares of renewable power, storage and/or demand response.
    Applications include integrated resource planning, investment planning,
    economic and policy analyses as well as basic research.
  doc_url: http://switch-model.org
  dev_url: https://github.com/switch-model/switch

extra:
  recipe-maintainers:
    - mfripp
